spring:
  application:
    name: bureauCepTest
  h2:
    console:
    
#H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2

spring.datasource.url=jdbc:h2:file:~/testDb
spring.datasource.username=cpc
spring.datasource.password=q1w2e3r4
spring.datasource.driver-class-name=org.h2.Driver